In [1]:
import pandas as pd
import IPython

# students_data dataframe
students_data = {
    'Student ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['John', 'Johnson', 'Williams', 'Emma', 'Matthew',
             'Smith', 'Daniel', 'Wilson', 'James', 'Micheal'],
    'Age': [20, 21, 19, 20, 22, 21, 20, 19, 22, 20],
    'Grade': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Male'],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Dallas', 'Phoenix',
             'New York', 'London', 'London', 'Dallas', 'Phoenix'],
    'Math': [85, 90, 78, 92, 88, 75, 82, 95, 80, 85],
    'Science': [88, 92, 85, 90, 78, 94, 85, 88, 92, 85],
    'English': [90, 85, 88, 92, 85, 90, 78, 94, 85, 88],
    'History': [82, 95, 80, 85, 88, 92, 85, 90, 78, 94]
}

# Create DataFrame
students_df = pd.DataFrame(students_data)

#print('Before Index : \n')
display(students_df)

#syntax : dataframeName.index=['','','']
#students_df.index=['I1','I2','I3','I4','I5','I6','I7','I8','I9','I10']
#students_df.index=students_df['Student ID']

#print('\n After Index: \n')
#display(students_df)

,Student ID,Name,Age,Grade,Gender,City,Math,Science,English,History
0,101,John,20,A,Male,New York,85,88,90,82
1,102,Johnson,21,B,Female,Los Angeles,90,92,85,95
2,103,Williams,19,A,Male,Chicago,78,85,88,80
3,104,Emma,20,B,Female,Dallas,92,90,92,85
4,105,Matthew,22,A,Male,Phoenix,88,78,85,88
5,106,Smith,21,B,Female,New York,75,94,90,92
6,107,Daniel,20,A,Male,London,82,85,78,85
7,108,Wilson,19,B,Female,London,95,88,94,90
8,109,James,22,A,Male,Dallas,80,92,85,78
9,110,Micheal,20,B,Male,Phoenix,85,85,88,94

In [2]:
#print('--------print only specific row/record------\n')
#syntax: df.iloc[rows,cols]

In [3]:
#print(students_df.loc['I9',:])
#print(students_df.iloc[9,:])


#display(students_df.iloc[:4,:3])
#display(students_df.iloc[1:3,4:6])
#display(students_df.iloc[[4,1,5] , 1:3])
#display(students_df.iloc[1:3 ,[4,1,5] ])
#display(students_df.iloc[[4,1,5] , [7,9]])
#display(students_df.loc[[0,3,6], ['Name','Age','City']])

In [4]:
students_df['English'].describe()

count    10.000000
mean     87.500000
std       4.527693
min      78.000000
25%      85.000000
50%      88.000000
75%      90.000000
max      94.000000
Name: English, dtype: float64

In [5]:
students_df[
            (students_df['Age']==20)
            &
            (students_df['Gender']=='Male')
            &
            (students_df['Math']>=80)
            ]

,Student ID,Name,Age,Grade,Gender,City,Math,Science,English,History
0,101,John,20,A,Male,New York,85,88,90,82
6,107,Daniel,20,A,Male,London,82,85,78,85
9,110,Micheal,20,B,Male,Phoenix,85,85,88,94

In [7]:
students_df['Total']=(
                        students_df['Math']
                        +
                        students_df['Science']
                        +
                        students_df['English']
                        +
                        students_df['History']
                    )
display(students_df)

,Student ID,Name,Age,Grade,Gender,City,Math,Science,English,History,Total
0,101,John,20,A,Male,New York,85,88,90,82,345
1,102,Johnson,21,B,Female,Los Angeles,90,92,85,95,362
2,103,Williams,19,A,Male,Chicago,78,85,88,80,331
3,104,Emma,20,B,Female,Dallas,92,90,92,85,359
4,105,Matthew,22,A,Male,Phoenix,88,78,85,88,339
5,106,Smith,21,B,Female,New York,75,94,90,92,351
6,107,Daniel,20,A,Male,London,82,85,78,85,330
7,108,Wilson,19,B,Female,London,95,88,94,90,367
8,109,James,22,A,Male,Dallas,80,92,85,78,335
9,110,Micheal,20,B,Male,Phoenix,85,85,88,94,352

In [ ]:
Engineering=(students_df['Math']+students_df['Science'])/2
Engineering.head(3)
Engineering.tail(2)

8    86.0
9    85.0
dtype: float64

In [ ]:
students_df.sort_values(by='Total')

,Student ID,Name,Age,Grade,Gender,City,Math,Science,English,History,Total
I7,107,Daniel,20,A,Male,London,82,85,78,85,330
I3,103,Williams,19,A,Male,Chicago,78,85,88,80,331
I9,109,James,22,A,Male,Dallas,80,92,85,78,335
I5,105,Matthew,22,A,Male,Phoenix,88,78,85,88,339
I1,101,John,20,A,Male,New York,85,88,90,82,345
I6,106,Smith,21,B,Female,New York,75,94,90,92,351
I10,110,Micheal,20,B,Male,Phoenix,85,85,88,94,352
I4,104,Emma,20,B,Female,Dallas,92,90,92,85,359
I2,102,Johnson,21,B,Female,Los Angeles,90,92,85,95,362
I8,108,Wilson,19,B,Female,London,95,88,94,90,367

In [ ]:
students_df.sort_values(by='Total',ascending=False)

   Student ID      Name  Age Grade  Gender         City  Math  Science  English  History  Total
7         108    Wilson   19     B  Female       London    95       88       94       90    367
1         102   Johnson   21     B  Female  Los Angeles    90       92       85       95    362
3         104      Emma   20     B  Female       Dallas    92       90       92       85    359
9         110   Micheal   20     B    Male      Phoenix    85       85       88       94    352
5         106     Smith   21     B  Female     New York    75       94       90       92    351
0         101      John   20     A    Male     New York    85       88       90       82    345
4         105   Matthew   22     A    Male      Phoenix    88       78       85       88    339
8         109     James   22     A    Male       Dallas    80       92       85       78    335
2         103  Williams   19     A    Male      Chicago    78       85       88       80    331
6         107    Daniel   20     A    Male       London    82       85       78       85    330

In [11]:
import os
os.getcwd()

'e:\\MCA\\sem 2\\DAV\\code'